## use it to upgrade and reboot target hosts
- hosts: target_hosts
  tasks:
    - name: upgrade all packages
      yum: name=* state=latest
      become: true

    - name: Check for reboot hint.
      shell: LAST_KERNEL=$(rpm -q --last kernel | perl -pe 's/^kernel-(\S+).*/$1/' | head -1); CURRENT_KERNEL=$(uname -r); if [ $LAST_KERNEL != $CURRENT_KERNEL ]; then echo 'reboot'; else echo 'no'; fi
      ignore_errors: true
      register: reboot_hint
      become: true

    - name: Rebooting ...
      command: shutdown -r now "Reboot required for updated kernel"
      async: 0
      poll: 0
      ignore_errors: true
      when: reboot_hint.stdout.find("reboot") != -1
      register: rebooting
      become: true

    - name: Wait for thing to reboot...
      pause: seconds=75
      when: rebooting|changed
      become: true
